#!/usr/bin/env python3
"""Export the compact manuscript appendices from the existing frozen outputs.

Run from the repository root: python3 writing/make_appendix_assets.py
Only the five manuscript assets are written; authoritative replication outputs
are read-only. Cabinet registry fields come from the tracked composition export.
The original registry source annotation identifies the underlying registry.
If the raw registry exists, its consumed fields must agree with that export. No generated/cabinet_party_sets or release is required.

Requires Python 3.10+, matplotlib, and pandas.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
from datetime import date
from fractions import Fraction
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ARTIFACT_ROOT = ROOT / 'processing/Processing/output/paper'
MANUSCRIPT = ROOT / 'writing/submission_inversions_review/manuscript'
FIGURE_STEM = 'cabinet_membership_inversions'
YEARS = (2014, 2018, 2022)


def read_rows(path: Path, required: set[str]) -> list[dict[str, str]]:
    if not path.is_file():
        raise ValueError(f'Missing authoritative CSV: {path}')
    with path.open(encoding='utf-8-sig', newline='') as stream:
        reader = csv.DictReader(stream)
        headers = reader.fieldnames or []
        check(bool(headers) and len(headers) == len(set(headers)),
              f'Missing or duplicate CSV headers: {path}')
        check(required <= set(headers),
              f'Missing columns in {path}: {sorted(required - set(headers))}')
        rows = list(reader)
    check(bool(rows), f'No authoritative rows: {path}')
    for number, row in enumerate(rows, 1):
        check(None not in row and None not in row.values(),
              f'Malformed CSV data row {number}: {path}')
    return rows


def check(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def one(rows, **keys):
    selected = [r for r in rows if all(str(r[k]) == str(v) for k, v in keys.items())]
    check(len(selected) == 1, f'Expected one authoritative row for {keys}; got {len(selected)}')
    return selected[0]


def unique(rows, keys, source):
    seen = set()
    for row in rows:
        key = tuple(row[k] for k in keys)
        check(key not in seen, f'Duplicate selection in {source}: {dict(zip(keys, key))}')
        seen.add(key)


def numeric(value, context):
    result = float(value)
    check(math.isfinite(result), f'Non-finite numeric value: {context}')
    return result



def tex(value: str) -> str:
    return value.replace('&', r'\&').replace('_', r'\_').replace('%', r'\%')


def inversion(row) -> bool:
    # Classify before rounding, directly from the fixed integer electoral vector.
    return int(row['seats']) >= 257 and 2 * int(row['votes']) < int(row['national_vote_total'])


def source_comment(path: Path) -> str:
    return f'% Generated by writing/make_appendix_assets.py; do not edit.\n% source: {path.relative_to(ROOT)}\n'


def cabinet_table(rows) -> str:
    lines = [r'''\begingroup
\small
\setlength{\tabcolsep}{5pt}
\renewcommand{\arraystretch}{1.0}
\setlength{\LTpre}{4pt}
\setlength{\LTpost}{4pt}
\begin{longtable}{@{}L{0.08\textwidth}L{0.78\textwidth}r@{}}
\caption{Distinct election-year cabinet party sets}\label{tab:full-cabinet-composition}\\
\toprule
Set & Election-year member parties & Days \\
\midrule
\endfirsthead
\multicolumn{3}{@{}l}{\small Table \thetable\ (continued)}\\
\toprule
Set & Election-year member parties & Days \\
\midrule
\endhead
\midrule
\multicolumn{3}{r@{}}{\footnotesize Continued on next page}\\
\endfoot
\bottomrule
\endlastfoot''']
    administrations = {'dilma_2': 'Dilma Rousseff (2014 election)',
                       'temer': 'Michel Temer (2014 election)',
                       'bolsonaro': 'Jair Bolsonaro (2018 election)',
                       'lula_3': 'Lula III (2022 election)'}
    previous = None
    for row in rows:
        administration = row['administrations']
        if administration != previous:
            check(administration in administrations, f'Unexpected administration: {administration}')
            lines.append(r'\addlinespace[4pt]\multicolumn{3}{@{}l}{\textit{'+administrations[administration]+r'}}\\*')
            previous = administration
        dagger = r'\(^{\dagger}\)' if int(row['provisional_days']) else ''
        lines.append(f"{row['display_label']}{dagger} & {tex(row['canonical_membership'].replace(';', ', '))} & {row['total_observed_days']} " + r'\\')
    lines += [r'''\end{longtable}
\noindent\footnotesize\textit{Note:} Days sum actual covered dates across appearances, not first-to-last spans. \(\dagger\): set includes provisionally coded days. Full histories and coding details remain in the replication files.
\endgroup''']
    return '\n'.join(lines)+'\n'


def interval_table(rows, raw) -> str:
    lines = [r'''\begin{table}[!htbp]
\centering\small
\caption{All baseline minimal connected winning intervals}
\label{tab:minimal-connected-winning-intervals}
\setlength{\tabcolsep}{8pt}
\renewcommand{\arraystretch}{1.0}
\begin{tabular}{@{}llrrr@{}}
\toprule
Election & Interval endpoints & Vote \% & Seats & \(d_C\) \\
\midrule''']
    previous = rows[0]['election_year']
    for row in rows:
        year = row['election_year']
        if year != previous:
            lines.append(r'\addlinespace[4pt]')
        previous = year
        exact = one(raw, election=year, ideological_universe='seat_winning', k=0,
                    left_endpoint=row['start_party'], right_endpoint=row['end_party'])
        marker = r'\(^{*}\)' if inversion(exact) else ''
        endpoints = tex(row['start_party'])+'--'+tex(row['end_party'])+marker
        lines.append(f"{year} & {endpoints} & {100*float(row['vote_share']):.2f} & {row['seats']} & {float(row['seat_diff']):.2f} "+r'\\')
    lines += [r'''\bottomrule
\end{tabular}
\par\vspace{4pt}\begin{minipage}{\textwidth}\footnotesize\textit{Note:} Each interval contains all seat-winning parties between its endpoints in the Figure~\ref{fig:minimal-connected-inversions} election-year order. \(*\): inversion, classified before rounding; vote shares use all valid federal-deputy votes.
\end{minipage}
\end{table}''']
    return '\n'.join(lines)+'\n'


def contribution_table(rows) -> str:
    lines = [r'''\begin{table}[!htbp]
\centering\small
\caption{Selected member-party contributions}
\label{tab:coalition-party-component-extremes}
\setlength{\tabcolsep}{4pt}
\renewcommand{\arraystretch}{1.15}
\begin{tabularx}{\textwidth}{@{}L{0.20\textwidth}*{4}{>{\raggedright\arraybackslash}X}@{}}
\toprule
Case & \multicolumn{2}{c}{Within-district \(A_i\)} & \multicolumn{2}{c}{Between-district \(B_i\)} \\
\cmidrule(lr){2-3}\cmidrule(l){4-5}
 & Positive & Negative & Positive & Negative \\
\midrule''']
    for row in rows:
        if row['domain'] == 'cabinet':
            label = f"Cabinet\n{row['election']}/{row['cabinet_period']}"
        else:
            label = f"Baseline\n{row['election']}/{tex(row['coalition_start_party'])}--{tex(row['coalition_end_party'])}"
        cells = [label.replace('\n', r'\newline ')]
        for component in ('A', 'B'):
            for sign in ('positive', 'negative'):
                entries = []
                for rank in (1, 2):
                    prefix = f'{component}_{sign}_{rank}'
                    if row[f'{prefix}_party']:
                        entries.append(r'\mbox{'+tex(row[f'{prefix}_party'])+'} '+f"({float(row[f'{prefix}_value']):.2f})")
                cells.append(r'\newline '.join(entries) or '--')
        lines.append(' & '.join(cells)+r'\\ \addlinespace[3pt]')
    lines += [r'''\bottomrule
\end{tabularx}
\par\vspace{4pt}\begin{minipage}{\textwidth}\footnotesize\textit{Note:} Entries are the two largest positive and two most negative member contributions per component, in seats. Baseline denotes the seat-winning \(k=0\) interval. PODE is the election-year label for Podemos.
\end{minipage}
\end{table}''']
    return '\n'.join(lines)+'\n'


def count_table(rows) -> str:
    primary = [one(rows, election=y, k=1, ideological_universe='seat_winning') for y in YEARS]
    totals = tuple(sum(int(r[field]) for r in primary) for field in ('minimal_seat_majority_coalitions', 'minimal_inversions'))
    lines = [r'''\begin{table}[!htbp]
\centering\small
\caption{Minimal winning coalitions by ideological domain and party universe}
\label{tab:one-gap-summary}
\label{tab:ideological-universe-comparison}
\setlength{\tabcolsep}{6pt}
\renewcommand{\arraystretch}{1.12}
\begin{tabular}{@{}lcrrrr@{}}
\toprule
 & & \multicolumn{2}{c}{Seat-winning parties} & \multicolumn{2}{c}{All parties} \\
\cmidrule(lr){3-4}\cmidrule(l){5-6}
Election & \(k\) & Minimal majorities & Inversions & Minimal majorities & Inversions \\
\midrule''']
    for year in YEARS:
        if year != YEARS[0]:
            lines.append(r'\addlinespace[3pt]')
        for k in (0, 1):
            cells = [str(year), str(k)]
            for universe in ('seat_winning', 'all_parties'):
                row = one(rows, election=year, k=k, ideological_universe=universe)
                cells.extend([row['minimal_seat_majority_coalitions'], row['minimal_inversions']])
            lines.append(' & '.join(cells)+r'\\')
    lines += [r'''\bottomrule
\end{tabular}
\par\vspace{4pt}\begin{minipage}{\textwidth}\footnotesize\textit{Note:} Minimality is recomputed for each \(k\) and universe. The primary \(k=1\) rows sum to @MAJORITIES@ minimal majorities and @INVERSIONS@ inversions. The \(k=0\) and \(k=1\) rows are overlapping domains and are not pooled. Every vote share uses all valid federal-deputy votes in \(V\).
\end{minipage}
\end{table}''']
    return ('\n'.join(lines)+'\n').replace('@MAJORITIES@', str(totals[0])).replace('@INVERSIONS@', str(totals[1]))


def build_cabinet_figure(cases, orders) -> plt.Figure:
    """Two ordinal membership panels, with Figure 3's type, labels and PT diamond."""
    with plt.rc_context({'font.family': 'DejaVu Sans', 'pdf.fonttype': 42}):
        fig, axes = plt.subplots(2, 1, figsize=(6.4, 5.0))
        axes[0].set_position([.035, .78, .95, .08])
        axes[1].set_position([.035, .34, .95, .08])
        for ax, row, panel, name in zip(axes, cases, ('a', 'b'), ('Dilma Rousseff', 'Lula III'), strict=True):
            year = int(row['election_year'])
            order = orders[year]
            membership = set(row['canonical_membership'].split(';'))
            for party, position in zip(order['party'], order['ordinal_position'], strict=True):
                member = party in membership
                ax.plot(position, 0, linestyle='none', marker='D' if party=='PT' else 'o',
                        markersize=7 if party=='PT' else (6.2 if member else 4.5),
                        markerfacecolor='black' if member else 'white',
                        markeredgecolor='black' if member else '#777777',
                        markeredgewidth=.9, zorder=4)
            ax.set_xticks(order['ordinal_position'], order['party'], rotation=90,
                          fontsize=9, ha='center', va='top')
            for label in ax.get_xticklabels():
                label.set_fontweight('bold' if label.get_text() in membership else 'normal')
            ax.tick_params(axis='x', length=0, pad=7, labelrotation=90)
            ax.set_yticks([])
            for spine in ax.spines.values():
                spine.set_visible(False)
            # The light baseline spans the entire party order, not the coalition.
            ax.spines['bottom'].set_visible(True)
            ax.spines['bottom'].set_position(('data', 0))
            ax.spines['bottom'].set_bounds(1, len(order))
            ax.spines['bottom'].set_color('#cccccc')
            ax.spines['bottom'].set_linewidth(.55)
            ax.set_xlim(.35, len(order)+.65)
            ax.set_ylim(-.12, .38)
            start, end = (date.fromisoformat(row[field]) for field in ('first_observed', 'last_observed'))
            if start.month == end.month and start.year == end.year:
                dates = f'{start.day}–{end.day} {end:%B %Y}'
            else:
                dates = f'{start.day} {start:%B}–{end.day} {end:%B %Y}'
            # Dates and electoral quantities come from the cabinet registry.
            ax.set_title(f"({panel}) {name} | {year} election | set {row['display_label']}\n"
                         f"{dates} | {100*float(row['vote_share']):.2f}% votes, {row['seats']} seats",
                         fontsize=10, pad=5, linespacing=1.55)
        handles = [Line2D([], [], color='black', marker='o', linestyle='none', markersize=6.2, label='Cabinet member'),
                   Line2D([], [], color='#777777', markerfacecolor='white', marker='o', linestyle='none', markersize=4.5, label='Nonmember'),
                   Line2D([], [], color='black', marker='D', linestyle='none', markersize=7, label='PT (cabinet member)')]
        fig.legend(handles=handles, loc='lower center', bbox_to_anchor=(.5,.04),
                   ncol=3, frameon=False, fontsize=9, handletextpad=.45, columnspacing=1.4)
        fig.text(.5,.005,'Seat-winning parties ordered from left to right (equally spaced)',
                 ha='center', va='bottom', fontsize=9)
    return fig


CABINET_FIELDS = set("cabinet_party_set_id display_label election_year administrations canonical_membership total_observed_days established_days provisional_days first_observed last_observed observation_intervals occurrence_count vote_share votes national_vote_total seats scenario_id".split())


def generate(artifact_root: Path, manuscript_dir: Path) -> dict:
    sources = {
        'cabinets': artifact_root/'tables/table_appendix_cabinet_composition.csv',
        'intervals': artifact_root/'tables/table_appendix_minimal_connected_winning_intervals.csv',
        'contributions': artifact_root/'tables/table_coalition_party_component_extremes.csv',
        'counts': artifact_root/'tables/ideological_universe_comparison.csv',
        'minimal': artifact_root/'raw/ideology_k_gap_minimal_accounting_both_universes.csv',
        **{f'order_{year}': artifact_root/'raw'/f'ideology_order_{year}.csv' for year in YEARS},
    }
    fields = {
        'cabinets': CABINET_FIELDS,
        'intervals': set('election_year ideological_universe start_party end_party parties vote_share seats seat_diff'.split()),
        'contributions': set('case_identifier domain election ideological_universe k cabinet_period coalition_start_party coalition_end_party'.split()) | {
            f'{component}_{sign}_{rank}_{field}' for component in ('A', 'B')
            for sign in ('positive', 'negative') for rank in (1, 2) for field in ('party', 'value', 'exact')},
        'counts': set('election k ideological_universe minimal_seat_majority_coalitions minimal_inversions'.split()),
        'minimal': set('election k ideological_universe ideological_party_count coalition_id left_endpoint right_endpoint votes national_vote_total vote_share seats d_C inversion minimal_seat_majority'.split()),
        **{f'order_{year}': set('election_year ideological_universe ordinal_position party'.split()) for year in YEARS},
    }
    data = {key: read_rows(path, fields[key]) for key, path in sources.items()}
    cabinets = sorted(data['cabinets'], key=lambda r: r['display_label'])
    unique(cabinets, ('cabinet_party_set_id',), sources['cabinets'])
    unique(cabinets, ('display_label',), sources['cabinets'])
    # These are expected registry keys, not replacement empirical values.
    expected_labels = {f'{year % 100}-{i:02d}' for year, count in ((2014, 12), (2018, 18), (2022, 5)) for i in range(1, count+1)}
    check({r['display_label'] for r in cabinets} == expected_labels, 'Missing or unexpected cabinet registry labels')
    for row in cabinets:
        label = row['display_label']
        check(row['scenario_id'] == 'primary', f'Unexpected cabinet scenario: {label}')
        check(label.startswith(str(int(row['election_year']) % 100) + '-'), f'Cabinet election mismatch: {label}')
        members = row['canonical_membership'].split(';')
        check(all(members) and len(members) == len(set(members)), f'Ambiguous membership: {label}')
        intervals = sorted((date.fromisoformat(a), date.fromisoformat(b)) for a, b in json.loads(row['observation_intervals']))
        check(bool(intervals) and all(a < b for a, b in intervals), f'Invalid observation intervals: {label}')
        check(all(b <= c for (_, b), (c, _) in zip(intervals, intervals[1:])), f'Overlapping observation intervals: {label}')
        days = sum((b-a).days for a, b in intervals)
        check(days == int(row['total_observed_days']) == int(row['established_days']) + int(row['provisional_days']), f'Covered-day mismatch: {label}')
        check(len(intervals) == int(row['occurrence_count']), f'Occurrence count mismatch: {label}')
        check(intervals[0][0] == date.fromisoformat(row['first_observed']) and (intervals[-1][1] - date.fromisoformat(row['last_observed'])).days == 1, f'Observation endpoints mismatch: {label}')
        check(math.isclose(numeric(row['vote_share'], label), int(row['votes']) / int(row['national_vote_total']), rel_tol=1e-14), f'Vote share mismatch: {label}')
    registry = artifact_root/'raw/cabinet_party_sets.csv'
    if registry.exists():
        raw = read_rows(registry, CABINET_FIELDS)
        unique(raw, ('cabinet_party_set_id',), registry)
        check(len(raw) == len(cabinets), 'Raw registry/composition row count mismatch')
        for row in cabinets:
            counterpart = one(raw, cabinet_party_set_id=row['cabinet_party_set_id'])
            check(all(row[k] == counterpart[k] for k in CABINET_FIELDS), f"Ambiguous registry/composition inputs: {row['display_label']}")
    orders = {}
    for year in YEARS:
        rows = data[f'order_{year}']
        check(all(r['election_year'] == str(year) and r['ideological_universe'] == 'seat_winning' for r in rows), f'Unexpected party-order domain: {year}')
        unique(rows, ('party',), sources[f'order_{year}'])
        rows = sorted(rows, key=lambda r: int(r['ordinal_position']))
        check([int(r['ordinal_position']) for r in rows] == list(range(1, len(rows)+1)) and sum(r['party'] == 'PT' for r in rows) == 1, f'Invalid ordinal party order: {year}')
        orders[year] = pd.DataFrame({'party': [r['party'] for r in rows], 'ordinal_position': [int(r['ordinal_position']) for r in rows]})
    minimal = data['minimal']
    unique(minimal, ('election', 'ideological_universe', 'k', 'coalition_id'), sources['minimal'])
    expected_domains = {(str(y), u, str(k)) for y in YEARS for u in ('seat_winning', 'all_parties') for k in (0, 1)}
    unique(data['counts'], ('election', 'ideological_universe', 'k'), sources['counts'])
    check({(r['election'], r['ideological_universe'], r['k']) for r in data['counts']} == expected_domains, 'Missing or unexpected count-table domains')
    check({(r['election'], r['ideological_universe'], r['k']) for r in minimal} == expected_domains, 'Missing or unexpected minimal-accounting domains')
    for row in minimal:
        check(row['minimal_seat_majority'] == 'true' and (row['inversion'] == 'true') == inversion(row), 'Inconsistent minimal-accounting classification')
    for year, universe, k in sorted(expected_domains):
        row = one(data['counts'], election=year, ideological_universe=universe, k=k)
        domain = [r for r in minimal if (r['election'], r['ideological_universe'], r['k']) == (year, universe, k)]
        check((int(row['minimal_seat_majority_coalitions']), int(row['minimal_inversions'])) == (len(domain), sum(inversion(r) for r in domain)), f'Count/export mismatch: {year}/{universe}/{k}')
    for year in YEARS:
        sizes = {int(r['ideological_party_count']) for r in minimal if r['election'] == str(year) and r['ideological_universe'] == 'seat_winning'}
        check(sizes == {len(orders[year])}, f'Missing or inconsistent party-order rows: {year}')
    baseline = [r for r in minimal if r['ideological_universe'] == 'seat_winning' and r['k'] == '0']
    intervals = data['intervals']
    unique(intervals, ('election_year', 'start_party', 'end_party'), sources['intervals'])
    check({(r['election_year'], r['start_party'], r['end_party']) for r in intervals} == {(r['election'], r['left_endpoint'], r['right_endpoint']) for r in baseline}, 'Missing or unexpected baseline intervals')
    for row in intervals:
        check(row['ideological_universe'] == 'seat_winning', 'Unexpected baseline universe')
        order = list(orders[int(row['election_year'])]['party'])
        check(row['start_party'] in order and row['end_party'] in order, 'Baseline endpoint outside party order')
        members = order[order.index(row['start_party']):order.index(row['end_party'])+1]
        check(members == row['parties'].split(', '), f'Endpoint membership mismatch: {row}')
        exact = one(baseline, election=row['election_year'], left_endpoint=row['start_party'], right_endpoint=row['end_party'])
        check(row['seats'] == exact['seats'] and all(math.isclose(numeric(row[a], a), numeric(exact[b], b), rel_tol=1e-13) for a, b in (('vote_share', 'vote_share'), ('seat_diff', 'd_C'))), 'Baseline table/accounting mismatch')
    intervals = sorted(intervals, key=lambda r: (int(r['election_year']), list(orders[int(r['election_year'])]['party']).index(r['start_party'])))
    cases = [one(cabinets, display_label=label) for label in ('14-05', '22-01')]
    check({r['display_label'] for r in cabinets if inversion(r)} == {r['display_label'] for r in cases}, 'Missing or unexpected inverted cabinet sets')
    for row in cases:
        check(set(row['canonical_membership'].split(';')) <= set(orders[int(row['election_year'])]['party']), 'Cabinet member outside represented party order')
        check(int(row['occurrence_count']) == 1, 'Figure date range would hide recurrence gaps')
    unique(data['contributions'], ('case_identifier',), sources['contributions'])
    selected = [one(data['contributions'], domain='cabinet', cabinet_period=label) for label in ('14-05', '22-01')]
    selected.append(one(data['contributions'], domain='ideological', election=2022, ideological_universe='seat_winning', k=0, coalition_start_party='MDB', coalition_end_party='UNIÃO'))
    for row in selected:
        for component in ('A', 'B'):
            for sign in ('positive', 'negative'):
                parties, values = [], []
                for rank in (1, 2):
                    prefix = f'{component}_{sign}_{rank}'
                    party, value, exact = (row[f'{prefix}_{field}'] for field in ('party', 'value', 'exact'))
                    check(bool(party) == bool(value) == bool(exact), f'Incomplete contribution: {prefix}')
                    if party:
                        parties.append(party)
                        number = numeric(value, prefix)
                        check(math.isclose(number, float(Fraction(exact.replace('//', '/'))), rel_tol=1e-13), f'Contribution/exact mismatch: {prefix}')
                        check(number > 0 if sign == 'positive' else number < 0, f'Contribution sign mismatch: {prefix}')
                        values.append(number)
                check(len(parties) == len(set(parties)) and values == sorted(values, reverse=sign == 'positive'), f'Duplicate or unordered contributions: {component}/{sign}')
    outputs = {
        'table_appendix_cabinet_membership_compact.tex': (registry, cabinet_table(cabinets)),
        'table_appendix_baseline_intervals_compact.tex': (sources['intervals'], interval_table(intervals, minimal)),
        'table_appendix_selected_party_contributions.tex': (sources['contributions'], contribution_table(selected)),
        'table_appendix_domain_counts_compact.tex': (sources['counts'], count_table(data['counts'])),
    }
    # Preserve the source annotations even with --artifact-root elsewhere.
    manuscript_dir.mkdir(parents=True, exist_ok=True)
    for name, (path, content) in outputs.items():
        canonical = DEFAULT_ARTIFACT_ROOT / path.relative_to(artifact_root)
        (manuscript_dir/name).write_text(source_comment(canonical)+content, encoding='utf-8')
    figure = build_cabinet_figure(cases, orders)
    try:
        figure.canvas.draw()
        renderer = figure.canvas.get_renderer()
        labels = [label for ax in figure.axes for label in ax.get_xticklabels()]
        check(all(label.get_rotation() == 90 for label in labels), 'Party labels must remain vertical')
        boxes = [item.get_window_extent(renderer) for item in [*labels, *(ax.title for ax in figure.axes), *figure.texts, *figure.legends]]
        check(all(figure.bbox.contains(bb.x0, bb.y0) and figure.bbox.contains(bb.x1, bb.y1) for bb in boxes), 'Figure label clipped')
        check(not any(a.overlaps(b) for i, a in enumerate(boxes) for b in boxes[i+1:]), 'Overlapping figure labels')
        with plt.rc_context({'pdf.fonttype': 42}):
            figure.savefig(manuscript_dir/(FIGURE_STEM+'.pdf'), facecolor='white', metadata={'CreationDate': None, 'ModDate': None})
    finally:
        plt.close(figure)
    return {
        'status': 'passed',
        'outputs': [*outputs, FIGURE_STEM+'.pdf'],
        'cabinet_sets': len(cabinets), 'baseline_intervals': len(intervals), 'selected_cases': len(selected),
        'figure_label_overlap_and_clipping_checks': 'passed',
    }


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--artifact-root',type=Path,default=DEFAULT_ARTIFACT_ROOT)
    parser.add_argument('--manuscript-dir',type=Path,default=MANUSCRIPT)
    args=parser.parse_args()
    print(json.dumps(generate(args.artifact_root.resolve(),args.manuscript_dir.resolve()),indent=2,ensure_ascii=False))


if __name__=='__main__':
    main()
