#!/usr/bin/env python3
"""Render all six manuscript tables from compact canonical scientific CSVs."""
from __future__ import annotations

import argparse
import csv
import json
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ARTIFACT_ROOT = ROOT / 'build/results/domains'
MANUSCRIPT = ROOT / 'build/assets'
FIGURE_STEM = 'cabinet_membership_inversions'
YEARS = (2014, 2018, 2022)


def read_rows(path: Path, required: set[str]) -> list[dict[str, str]]:
    if not path.is_file():
        raise ValueError(f'Missing authoritative CSV: {path}')
    with path.open(encoding='utf-8-sig', newline='') as stream:
        reader = csv.DictReader(stream)
        headers = reader.fieldnames or []
        check(bool(headers) and len(headers) == len(set(headers)),
              f'Missing or duplicate CSV headers: {path}')
        check(required <= set(headers),
              f'Missing columns in {path}: {sorted(required - set(headers))}')
        rows = list(reader)
    check(bool(rows), f'No authoritative rows: {path}')
    for number, row in enumerate(rows, 1):
        check(None not in row and None not in row.values(),
              f'Malformed CSV data row {number}: {path}')
    return rows


def check(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def one(rows, **keys):
    selected = [r for r in rows if all(str(r[k]) == str(v) for k, v in keys.items())]
    check(len(selected) == 1, f'Expected one authoritative row for {keys}; got {len(selected)}')
    return selected[0]


def unique(rows, keys, source):
    seen = set()
    for row in rows:
        key = tuple(row[k] for k in keys)
        check(key not in seen, f'Duplicate selection in {source}: {dict(zip(keys, key))}')
        seen.add(key)


def tex(value: str) -> str:
    return value.replace('&', r'\&').replace('_', r'\_').replace('%', r'\%')


def source_comment(path: Path) -> str:
    return f'% Generated by scripts/make_tables.py; do not edit.\n% source: {path.relative_to(ROOT)}\n'


def cabinet_table(rows) -> str:
    lines = [r'''\begingroup
\small
\setlength{\tabcolsep}{5pt}
\renewcommand{\arraystretch}{1.0}
\setlength{\LTpre}{4pt}
\setlength{\LTpost}{4pt}
\begin{longtable}{@{}L{0.08\textwidth}L{0.78\textwidth}r@{}}
\caption{Distinct election-year cabinet party sets}\label{tab:full-cabinet-composition}\\
\toprule
Set & Election-year member parties & Days \\
\midrule
\endfirsthead
\multicolumn{3}{@{}l}{\small Table \thetable\ (continued)}\\
\toprule
Set & Election-year member parties & Days \\
\midrule
\endhead
\midrule
\multicolumn{3}{r@{}}{\footnotesize Continued on next page}\\
\endfoot
\bottomrule
\endlastfoot''']
    administrations = {'dilma_2': 'Dilma Rousseff (2014 election)',
                       'temer': 'Michel Temer (2014 election)',
                       'bolsonaro': 'Jair Bolsonaro (2018 election)',
                       'lula_3': 'Lula III (2022 election)'}
    previous = None
    for row in rows:
        administration = row['administrations']
        if administration != previous:
            check(administration in administrations, f'Unexpected administration: {administration}')
            lines.append(r'\addlinespace[4pt]\multicolumn{3}{@{}l}{\textit{'+administrations[administration]+r'}}\\*')
            previous = administration
        dagger = r'\(^{\dagger}\)' if int(row['provisional_days']) else ''
        lines.append(f"{row['display_label']}{dagger} & {tex(row['canonical_membership'].replace(';', ', '))} & {row['total_observed_days']} " + r'\\')
    lines += [r'''\end{longtable}
\noindent\footnotesize\textit{Note:} Days sum actual covered dates across appearances, not first-to-last spans. \(\dagger\): set includes provisionally coded days. Full histories and coding details remain in the replication files.
\endgroup''']
    return '\n'.join(lines)+'\n'


def interval_table(rows) -> str:
    lines = [r'''\begin{table}[!htbp]
\centering\small
\caption{All baseline minimal connected winning intervals}
\label{tab:minimal-connected-winning-intervals}
\setlength{\tabcolsep}{8pt}
\renewcommand{\arraystretch}{1.0}
\begin{tabular}{@{}llrrr@{}}
\toprule
Election & Interval endpoints & Vote \% & Seats & \(d_C\) \\
\midrule''']
    previous = rows[0]['election_year']
    for row in rows:
        year = row['election_year']
        if year != previous:
            lines.append(r'\addlinespace[4pt]')
        previous = year
        marker = r'\(^{*}\)' if row['coalition_inversion'].lower() == 'true' else ''
        endpoints = tex(row['start_party'])+'--'+tex(row['end_party'])+marker
        lines.append(f"{year} & {endpoints} & {100*float(row['vote_share']):.2f} & {row['seats']} & {float(row['seat_diff']):.2f} "+r'\\')
    lines += [r'''\bottomrule
\end{tabular}
\par\vspace{4pt}\begin{minipage}{\textwidth}\footnotesize\textit{Note:} Each interval contains all seat-winning parties between its endpoints in the Figure~\ref{fig:minimal-connected-inversions} election-year order. \(*\): inversion, classified before rounding; vote shares use all valid federal-deputy votes.
\end{minipage}
\end{table}''']
    return '\n'.join(lines)+'\n'


def contribution_table(rows) -> str:
    lines = [r'''\begin{table}[!htbp]
\centering\small
\caption{Selected member-party contributions}
\label{tab:coalition-party-component-extremes}
\setlength{\tabcolsep}{4pt}
\renewcommand{\arraystretch}{1.15}
\begin{tabularx}{\textwidth}{@{}L{0.20\textwidth}*{4}{>{\raggedright\arraybackslash}X}@{}}
\toprule
Case & \multicolumn{2}{c}{Within-district \(A_i\)} & \multicolumn{2}{c}{Between-district \(B_i\)} \\
\cmidrule(lr){2-3}\cmidrule(l){4-5}
 & Positive & Negative & Positive & Negative \\
\midrule''']
    for row in rows:
        if row['domain'] == 'cabinet':
            label = f"Cabinet\n{row['election']}/{row['cabinet_period']}"
        else:
            label = f"Baseline\n{row['election']}/{tex(row['coalition_start_party'])}--{tex(row['coalition_end_party'])}"
        cells = [label.replace('\n', r'\newline ')]
        for component in ('A', 'B'):
            for sign in ('positive', 'negative'):
                entries = []
                for rank in (1, 2):
                    prefix = f'{component}_{sign}_{rank}'
                    if row[f'{prefix}_party']:
                        entries.append(r'\mbox{'+tex(row[f'{prefix}_party'])+'} '+f"({float(row[f'{prefix}_value']):.2f})")
                cells.append(r'\newline '.join(entries) or '--')
        lines.append(' & '.join(cells)+r'\\ \addlinespace[3pt]')
    lines += [r'''\bottomrule
\end{tabularx}
\par\vspace{4pt}\begin{minipage}{\textwidth}\footnotesize\textit{Note:} Entries are the two largest positive and two most negative member contributions per component, in seats. Baseline denotes the seat-winning \(k=0\) interval. PODE is the election-year label for Podemos.
\end{minipage}
\end{table}''']
    return '\n'.join(lines)+'\n'


def count_table(rows) -> str:
    primary = [one(rows, election=y, k=1, ideological_universe='seat_winning') for y in YEARS]
    totals = tuple(sum(int(r[field]) for r in primary) for field in ('minimal_seat_majority_coalitions', 'minimal_inversions'))
    lines = [r'''\begin{table}[!htbp]
\centering\small
\caption{Minimal winning coalitions by ideological domain and party universe}
\label{tab:one-gap-summary}
\label{tab:ideological-universe-comparison}
\setlength{\tabcolsep}{6pt}
\renewcommand{\arraystretch}{1.12}
\begin{tabular}{@{}lcrrrr@{}}
\toprule
 & & \multicolumn{2}{c}{Seat-winning parties} & \multicolumn{2}{c}{All parties} \\
\cmidrule(lr){3-4}\cmidrule(l){5-6}
Election & \(k\) & Minimal majorities & Inversions & Minimal majorities & Inversions \\
\midrule''']
    for year in YEARS:
        if year != YEARS[0]:
            lines.append(r'\addlinespace[3pt]')
        for k in (0, 1):
            cells = [str(year), str(k)]
            for universe in ('seat_winning', 'all_parties'):
                row = one(rows, election=year, k=k, ideological_universe=universe)
                cells.extend([row['minimal_seat_majority_coalitions'], row['minimal_inversions']])
            lines.append(' & '.join(cells)+r'\\')
    lines += [r'''\bottomrule
\end{tabular}
\par\vspace{4pt}\begin{minipage}{\textwidth}\footnotesize\textit{Note:} Minimality is recomputed for each \(k\) and universe. The primary \(k=1\) rows sum to @MAJORITIES@ minimal majorities and @INVERSIONS@ inversions. The \(k=0\) and \(k=1\) rows are overlapping domains and are not pooled. Every vote share uses all valid federal-deputy votes in \(V\).
\end{minipage}
\end{table}''']
    return ('\n'.join(lines)+'\n').replace('@MAJORITIES@', str(totals[0])).replace('@INVERSIONS@', str(totals[1]))




def inversion_table(rows, components=True):
    lines=[r'\begin{tabularx}{\textwidth}{@{}llrrrrrr>{\raggedright\arraybackslash}X@{}}',r'\toprule',
        r'Election & Set & Days & Vote \% & Seats & \(d_C\) & \(A_C\) & \(B_C\) & Parties \\' if components else
        r'Election & Set & Days & Vote \% & Seats & \(q_C\) & \(d_C\) & \(R_C\) & Parties \\',r'\midrule']
    for r in rows:
        d,A=round(1000*float(r['d_C'])),round(1000*float(r['A_C']))
        values=[f'{d/1000:.3f}',f'{A/1000:.3f}',f'{(d-A)/1000:.3f}'] if components else [f"{float(r[k]):.3f}" for k in ('q_C','d_C','R_C')]
        lines.append(' & '.join([r['election_year'],r['display_label'],r['total_observed_days'],f"{100*float(r['vote_share']):.2f}",r['seats'],*values,tex(r['canonical_membership'].replace(';',', '))])+r' \\')
    lines.extend([r'\bottomrule',r'\end{tabularx}'])
    lines.append(r'\par\smallskip{\footnotesize Days sum actual appearances of each set; all inversion days are evidence-established.}')
    return '\n'.join(lines)


def minimal_ideological_table(rows):
    check(all(r['minimal_inversion'].lower() == 'true' for r in rows), 'Nonminimal ideological table row')
    lines = [r'\begin{tabular}{@{}lllrrrrrr@{}}', r'\toprule',
             r'Election & Start & End & Parties & Vote \% & Seats & \(d_C\) & \(A_C\) & \(B_C\) \\', r'\midrule']
    for row in sorted(rows, key=lambda r: tuple(int(r[k]) for k in ('election_year', 'ideology_start_index', 'ideology_end_index'))):
        d, a = round(1000 * float(row['d_C'])), round(1000 * float(row['A_C']))
        cells = [row['election_year'], tex(row['start_party']), tex(row['end_party']),
                 row['coalition_party_count'], f"{float(row['vote_share_pct']):.2f}", row['s_C'],
                 f'{d/1000:.3f}', f'{a/1000:.3f}', f'{(d-a)/1000:.3f}']
        lines.append(' & '.join(cells) + r' \\')
    return '\n'.join(lines + [r'\bottomrule', r'\end{tabular}']) + '\n'


def generate(artifact_root=DEFAULT_ARTIFACT_ROOT, manuscript_dir=MANUSCRIPT):
    accounting = artifact_root.parent / 'accounting'
    sources = {
        'cabinets': accounting / 'raw/cabinet_party_set_accounting.csv',
        'intervals': artifact_root / 'tables/table_appendix_minimal_connected_winning_intervals.csv',
        'contributions': accounting / 'tables/table_coalition_party_component_extremes.csv',
        'counts': artifact_root / 'tables/ideological_universe_comparison.csv',
        'minimal': accounting / 'tables/table_accounting_minimal_ideological.csv',
    }
    data = {k: read_rows(path, set()) for k, path in sources.items()}
    cabinets = sorted(data['cabinets'], key=lambda r: r['display_label'])
    unique(cabinets, ('cabinet_party_set_id',), sources['cabinets'])
    intervals = data['intervals']
    unique(intervals, ('election_year', 'start_party', 'end_party'), sources['intervals'])
    selected = [one(data['contributions'], domain='cabinet', cabinet_period=label) for label in ('14-05', '22-01')]
    selected.append(one(data['contributions'], domain='ideological', election=2022,
                        ideological_universe='seat_winning', k=0, coalition_start_party='MDB', coalition_end_party='UNIÃO'))
    inversions = [r for r in cabinets if r['coalition_inversion'].lower() == 'true']
    outputs = {
        'table_observed_inversion_decomposition.tex': ('cabinets', inversion_table(inversions) + '\n', False),
        'table_accounting_minimal_ideological.tex': ('minimal', minimal_ideological_table(data['minimal']), False),
        'table_appendix_cabinet_membership_compact.tex': ('cabinets', cabinet_table(cabinets), True),
        'table_appendix_baseline_intervals_compact.tex': ('intervals', interval_table(intervals), True),
        'table_appendix_selected_party_contributions.tex': ('contributions', contribution_table(selected), True),
        'table_appendix_domain_counts_compact.tex': ('counts', count_table(data['counts']), True),
    }
    manuscript_dir.mkdir(parents=True, exist_ok=True)
    for name, (key, content, annotated) in outputs.items():
        (manuscript_dir / name).write_text((source_comment(sources[key]) if annotated else '') + content, encoding='utf-8')
    print(f'Generated {len(outputs)} manuscript table fragments from compact canonical results.')


if __name__ == '__main__':
    generate()
